[build]
  command = "npm run build"
  publish = "dist/MoviesAPI/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API routes if you have any
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle assets correctly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200